# -*- encoding:utf-8 -*-
import json
mo = ["上海市", "不丹", "丹麥", "烏克蘭", "烏拉圭", "雲南省", "亞美尼亞", "以色列", "伊拉克", "伊朗", "俄羅斯", "保加利亞", "克羅地亞", "內蒙古自治區", "冰島", "幾內亞", "列支敦士登", "剛果（金）", "加拿大", "加納", "加蓬", "匈牙利", "北京市" , "北愛爾蘭", "北馬其頓", "南非", "卡塔爾", "盧旺達", "盧森堡", "印度", "印度尼西亞", "危地馬拉", "厄瓜多爾", "古巴", "台灣" , "吉林省", "哈薩克斯坦", "哥倫比亞", "哥斯達黎加", "喀麥隆", "四川省", "土耳其", "聖巴泰勒米", "聖文森特和格林納丁斯", "聖馬丁島", "聖馬力諾", "圭亞那", "埃及", "埃塞俄比亞", "塞內加爾", "塞爾維亞", "塞浦路斯", "塞舌爾", "墨西哥", "多哥", "多米尼加" , "大不列顛及北愛爾蘭聯合王國", "天津市", "奧地利", "委內瑞拉", "孟加拉國", "寧夏回族自治區", "安徽省", "安提瓜和巴布達", "安道爾", "尼日利亞", "尼泊爾", "山東省", "山西省", "巴勒斯坦", "巴基斯坦", "巴拉圭", "巴拿馬", "巴林", "巴西", "布基納法索", "希臘", "廣東省", "廣西壯族自治區", "德國", "意大利", "拉脫維亞", "挪威", "捷克", "摩爾多瓦", "摩洛哥", "摩納哥", "文萊", "斯威士蘭", "斯洛伐克", "斯洛文尼亞", "斯里蘭卡", "新加坡", "新疆維吾爾自治區", "新西蘭", "日本", "智利", "柬埔寨", "根西島", "格魯吉亞", "梵蒂岡", "比利時", "毛里塔尼亞", "江蘇省", "江西省", "沙特阿拉伯", "河北省", "河南省", "法國", "法屬圭亞那", "法屬波利尼西亞", "法羅群島", "波蘭", "波黑", "泰國", "澤西島", "洪都拉斯", "浙江省", "海南省", "湖北省", "湖南省", "澳大利亞", "澳門", "愛爾蘭", "愛沙尼亞", "牙買加", "特立尼達和多巴哥", "玻利維亞", "瑞典", "瑞士", "甘肅省", "留尼汪", "白俄羅斯", "直布羅陀", "福建省", "科威特", "科特瓦", "秘魯", "突尼斯", "立陶宛", "約旦", "納米比亞", "羅馬尼亞", "美國", "肯尼亞", "至尊公主郵輪", "芬蘭", "蘇丹", "蘇里南", "英國", "英國（含北愛爾蘭）", "荷蘭", "菲律賓", "葡萄牙", "蒙古", "西班牙", "西藏自治區", "貴州省", "赤道幾內亞" , "越南", "遼寧省", "重慶市", "鑽石公主號郵輪", "阿塞拜疆", "阿富汗", "阿爾及利亞", "阿爾巴尼亞", "阿曼", "阿根廷", "阿聯酋", "陝西省", "青海省", "韓國", "香港", "馬爾代夫", "馬提尼克", "馬來西亞", "馬耳他", "黎巴嫩", "黑龍江省"]
cn = ["上海市", "不丹", "丹麦", "乌克兰", "乌拉圭", "云南省", "亚美尼亚", "以色列", "伊拉克", "伊朗", "俄罗斯", "保加利亚", "克罗地亚", "内蒙古自治区", "冰岛", "几内亚", "列支敦士登", "刚果（金）", "加拿大", "加纳", "加蓬", "匈牙利", "北京市", "北爱尔兰", "北马其顿", "南非", "卡塔尔", "卢旺达", "卢森堡", "印度", "印度尼西亚", "危地马拉", "厄瓜多尔", "古巴", "台湾", "吉林省", "哈萨克斯坦", "哥伦比亚", "哥斯达黎加", "喀麦隆", "四川省", "土耳其", "圣巴泰勒米", "圣文森特和格林纳丁斯", "圣马丁岛", "圣马力诺", "圭亚那", "埃及", "埃塞俄比亚", "塞内加尔", "塞尔维亚", "塞浦路斯", "塞舌尔", "墨西哥", "多哥", "多米尼加", "大不列颠及北爱尔兰联合王国", "天津市", "奥地利", "委内瑞拉", "孟加拉国", "宁夏回族自治区", "安徽省", "安提瓜和巴布达", "安道尔", "尼日利亚", "尼泊尔", "山东省", "山西省", "巴勒斯坦", "巴基斯坦", "巴拉圭", "巴拿马", "巴林", "巴西", "布基纳法索", "希腊", "广东省", "广西壮族自治区", "德国", "意大利", "拉脱维亚", "挪威", "捷克", "摩尔多瓦", "摩洛哥", "摩纳哥", "文莱", "斯威士兰", "斯洛伐克", "斯洛文尼亚", "斯里兰卡", "新加坡", "新疆维吾尔自治区", "新西兰", "日本", "智利", "柬埔寨", "根西岛", "格鲁吉亚", "梵蒂冈", "比利时", "毛里塔尼亚", "江苏省", "江西省", "沙特阿拉伯", "河北省", "河南省", "法国", "法属圭亚那", "法属波利尼西亚", "法罗群岛", "波兰", "波黑", "泰国", "泽西岛", "洪都拉斯", "浙江省", "海南省", "湖北省", "湖南省", "澳大利亚", "澳门", "爱尔兰", "爱沙尼亚", "牙买加", "特立尼达和多巴哥", "玻利维亚", "瑞典", "瑞士", "甘肃省", "留尼汪", "白俄罗斯", "直布罗陀", "福建省", "科威特", "科特迪瓦", "秘鲁", "突尼斯", "立陶宛", "约旦", "纳米比亚", "罗马尼亚", "美国", "肯尼亚", "至尊公主邮轮", "芬兰", "苏丹", "苏里南", "英国", "英国（含北爱尔兰）", "荷兰", "菲律宾", "葡萄牙", "蒙古", "西班牙", "西藏自治区", "贵州省", "赤道几内亚", "越南", "辽宁省", "重庆市", "钻石公主号邮轮", "阿塞拜疆", "阿富汗", "阿尔及利亚", "阿尔巴尼亚", "阿曼", "阿根廷", "阿联酋", "陕西省", "青海省", "韩国", "香港", "马尔代夫", "马提尼克", "马来西亚", "马耳他", "黎巴嫩", "黑龙江省"]
en =["Shanghai", "Bhutan", "Denmark", "Ukraine", "Uruguay", "Yunnan Province", "Armenia", "Israel", "Iraq", "Iran", "Russia", "Bulgaria "," Croatia "," Inner Mongolia Autonomous Region "," Iceland "," Guinea "," Liechtenstein "," Congo (D) "," Canada "," Ghana "," Gabon "," Hungary "," Beijing " , "Northern Ireland", "Northern Macedonia", "South Africa", "Qatar", "Rwanda", "Luxembourg", "India", "Indonesia", "Guatemala", "Ecuador", "Cuba", "Taiwan" , "Jilin Province", "Kazakhstan", "Colombia", "Costa Rica", "Cameroon", "Sichuan Province", "Turkey", "St. Barthelemy", "St. Vincent and the Grenadines", "St. Martin "," San Marino "," Guyana "," Egypt "," Ethiopia "," Senegal "," Serbia "," Cyprus "," Seychelles "," Mexico "," Togo "," Dominica " , "United Kingdom of Great Britain and Northern Ireland", "Tianjin", "Austria", "Venezuela", "Bangladesh", "Ningxia Hui Autonomous Region", "Anhui Province", "Antigua and Barbuda", " Andorra "," Nigeria "," Nepal "," Shandong Province "," Shanxi Province "," Palestine "," Pakistan "," Paraguay "," Panama "," Bahrain "," Brazil "," Burkina Faso "," Greece "," Guangdong Province "," Guangxi Zhuang Autonomous Region "," Germany "," Italy "," Latvia "," Norway "," Czech "," Moldova "," Morocco "," Monaco "," Brunei ", "Swaziland", "Slovakia", "Slovenia", "Sri Lanka", "Singapore", "Xinjiang Uygur Autonomous Region", "New Zealand", "Japan", "Chile", "Cambodia", "Guernsey", "Georgia", "Vatican", "Belgium", "Mauritania", "Jiangsu Province", "Jiangxi Province", "Saudi Arabia", "Hebei Province", "Henan Province", "France", "French Guiana" , "French Polynesia", "Faroe Islands", "Poland", "Bosnia and Herzegovina", "Thailand", "Jersey", "Honduras", "Zhejiang Province", "Hainan Province", "Hubei Province", "Hunan Province", "Australia", "Macau", "Ireland", "Estonia", "Jamaica", "Trinidad and Tobago", "Bolivia", "Sweden", "Switzerland", "Gansu Province "," Reunion "," Belarus "," Gibraltar "," Fujian Province "," Kuwait "," Korea Watt", "Peru", "Tunisia", "Lithuania", "Jordan", "Namibia", "Romania", "United States", "Kenya", "Extreme Princess Cruises", "Finland", "Sudan", "Suriname "," United Kingdom "," United Kingdom (including Northern Ireland) "," Netherlands "," Philippines "," Portugal "," Mongolia "," Spain "," Tibet Autonomous Region "," Guizhou Province "," Equatorial Guinea " , "Vietnam", "Liaoning Province", "Chongqing", "Diamond Princess Cruise", "Azerbaijan", "Afghanistan", "Algeria", "Albania", "Oman", "Argentina", "UAE", "Shaanxi Province", "Qinghai Province", "Korea", "Hong Kong", "Maldives", "Martinique", "Malaysia", "Malta", "Lebanon", "Heilongjiang Province"]



dict = {}


for i in range(len(mo)):
   dict[mo[i]] = cn[i]


with open('mo_en.json', 'w',encoding="utf-8") as json_file:
    json.dump(dict, json_file,ensure_ascii = False)
